name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build-package:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
      env:
         ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Restore Packages
      run: nuget restore PullCanvasData2.sln
    - name: Compile Package
      working-directory: PullCanvasData2
      run: nuget pack PullCanvasData2.csproj -Build -Properties Configuration=Release -Properties BuildVersion=$(date "+%s")
    - uses: actions/upload-artifact@v3
      with:
        name: pca
        path: PullCanvasData2/PullCanvasData2*.nupkg

  deploy-package:
  
    runs-on: ubuntu-latest
    needs: build-package
    
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: pca
    - name: Run deploy script
      run: curl -vX PUT -u "uvadev:${{secrets.GITHUB_TOKEN}}" -F package="@$(echo PullCanvasData2.*.nupkg)" https://nuget.pkg.github.com/uvadev/
      shell: bash
